### ISSUE TITLE
Error with the automatic validation of the data end-point URL

### ISSUE THREAD

**Issue by marcomb** [theodi/open-data-certificate#1408] opened 2016-05-02 16:52 UTC
Hallo

We are testing the creation of ODI certificate on some data published into http://dati.trentino.it
The datasets we are testing are REST/JSON end-points (open services) published to from the same domain of the catalogue, but from the source web site (in this case the Municipality of Riva del Garda, TN)

This is the certificate
https://certificates.theodi.org/en/datasets/213882/certificate

Everything is OK, except the value of  "The API service endpoint is"
Where I get the errore "This data has failed automatic validation because the URL is not correct."

The API END-POINT is the following 
http://www.comune.rivadelgarda.tn.it/api/opendata/v2/content/search/classes%20'sala_pubblica'

What's wrong with my URL?
What is checking the automatic validation of the URL? a parameter? something else?
Couldn't I use a REST/JSON end-point?

Thanks for any help

**Comment by rachelwilson** [comment] 2021-06-21 16:09
Duplicate of https://github.com/theodi/open-data-certificate/issues/1411

**Closed by rachelwilson** 2021-06-21 16:09 UTC
