### ISSUE TITLE
Certificate integration issue

### ISSUE THREAD

**Issue by AsharBurney** [theodi/open-data-certificate#1468] opened 2017-06-16 07:20 UTC
I did not received any error while integrating ckan with open data certificates but I am not able to see any certificate integrated, I followed the link below.

http://extensions.ckan.org/extension/certificates/

Expected Behaviour

Certificates should be integrated after data set is uploaded.

After following command:

paster --plugin=ckanext-certificates fetch_certs -c /etc/ckan/default/development.ini
I got the following outcome:

> 2017-06-16 11:24:51,131 DEBUG [ckanext.certificates.commands] Database access initialised
> 2017-06-16 11:24:51,132 DEBUG [ckanext.certificates.commands] Site url filter (regex): ^https?://(www.)?localhost\:5000.*
> 2017-06-16 11:24:56,201 DEBUG [ckanext.certificates.client] Page URLs self: https://certificates.theodi.org/en/datasets.feed?domain=data.gov.uk&since=2017-06-16T06%3A24%3A51.132770Z last: https://certificates.data.gov.uk/en/datasets.feed?page=0&since=2017-06-16T06%3A24%3A51.132770Z
> 2017-06-16 11:24:56,202 INFO [ckanext.certificates.commands] Summary:
> None

If I am on the right track then please guide me what will be the next step and if I have made some mistake then please tell me what to do.

**Comment by quadrophobiac** [comment] 2017-06-20 11:39
duplicate of #1467

**Comment by rachelwilson** [comment] 2021-06-21 15:46
Closing as duplicate

**Closed by rachelwilson** 2021-06-21 15:46 UTC
